let token=localStorage.getItem('mfr_token'), me=null;const $=id=>document.getElementById(id);const api=async(path,opt={})=>{opt.headers={...(opt.headers||{}),...(token?{Authorization:'Bearer '+token}:{})};let r=await fetch('/api'+path,opt);let d=await r.json().catch(()=>({detail:'Server error'}));if(!r.ok)throw Error(d.detail||'Request failed');return d};
function showLogged(){ $('login').classList.add('hidden');$('dashboard').classList.remove('hidden');$('logout').classList.remove('hidden'); }
async function login(){try{let d=await api('/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('name').value,identifier:$('identifier').value})});token=d.token;localStorage.setItem('mfr_token',token);me=d.user;showLogged();await loadMe()}catch(e){$('loginmsg').textContent=e.message}}
$('logout').onclick=()=>{token=null;localStorage.removeItem('mfr_token');location.reload()};
async function loadMe(){try{me=await api('/me');$('welcome').textContent='Welcome, '+(me.Name||'Member');$('role').textContent=me.role==='admin'?'Administrator':'Family Member';$('admin').classList.toggle('hidden',me.role!=='admin');renderProfile(me);if(me.Person_id)await findMembers()}catch(e){$('loginmsg').textContent=e.message}}
function renderProfile(p){$('profile').innerHTML=`${p.has_photo?`<img class="profile" src="/api/members/${p.Person_id}/photo?x=${Date.now()}">`:''}<div class="item"><b>Name:</b> ${esc(p.Name)}</div><div class="item"><b>Person ID:</b> ${p.Person_id??'Admin'}</div><div class="item"><b>Mobile:</b> ${esc(p.Mobile||'N/A')}</div><div class="item"><b>Mail ID:</b> ${esc(p.Mail_id||'N/A')}</div><div class="item"><b>Date of Birth:</b> ${esc(p.DOB||'N/A')}</div><div class="item"><b>Date of Death:</b> ${esc(p.DOD||'N/A')}</div><div class="item"><b>Gender:</b> ${esc(p.Gender||'N/A')}</div>`}
function editMe(){if(!me.Person_id)return;showEdit(me)}
function showEdit(p){$('modalTitle').textContent='Edit Profile';$('modalBody').innerHTML=`<input id="eName" value="${attr(p.Name)}" placeholder="Name"><input id="eDob" value="${attr(p.DOB)}" placeholder="DOB (dd-mm-yyyy)"><input id="eDod" value="${attr(p.DOD)}" placeholder="DOD"><input id="eMobile" value="${attr(p.Mobile)}" placeholder="Mobile"><input id="eMail" value="${attr(p.Mail_id)}" placeholder="Mail ID"><input id="eGender" value="${attr(p.Gender)}" placeholder="Gender"><button onclick="saveEdit(${p.Person_id})">Save</button>`;$('modal').classList.remove('hidden')}
async function saveEdit(id){try{let body={Name:$('eName').value,DOB:$('eDob').value,DOD:$('eDod').value,Mobile:$('eMobile').value,Mail_id:$('eMail').value,Gender:$('eGender').value};me=await api('/members/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});closeModal();renderProfile(me)}catch(e){alert(e.message)}}
async function uploadPhoto(){let f=$('photo').files[0];if(!f||!me.Person_id)return alert('Select an image');let fd=new FormData();fd.append('file',f);try{await api('/members/'+me.Person_id+'/photo',{method:'POST',body:fd});await loadMe()}catch(e){alert(e.message)}}
async function findMembers(){if(!me.Person_id)return;try{let rows=await api('/relations/'+me.Person_id);let f=$('relFilter').value;rows=rows.filter(x=>f==='All'||x.relation===f);$('relations').innerHTML=rows.length?rows.map(x=>`<div class="item"><b>${esc(x.person.Name)}</b><br><span class="pill">${esc(x.relation)}</span><br>${esc(x.how_related||'')}</div>`).join(''):'<p class="muted">No members found for this relation.</p>'}catch(e){$('relations').textContent=e.message}}
async function findRelation(){let t=$('target').value.trim();if(!t)return;try{let ms=await api('/members?q='+encodeURIComponent(t));let p=ms.find(x=>x.Name.toLowerCase()===t.toLowerCase());if(!p)return $('relationResult').textContent='Person not found.';let r=await api('/relation/'+me.Person_id+'/'+p.Person_id);$('relationResult').innerHTML=r.found?`<div class="item"><b>${esc(p.Name)}</b> is <span class="pill">${esc(r.relation)}</span> of ${esc(me.Name)}<br>${esc(r.how_related||'')}</div>`:'<p class="muted">No relation recorded.</p>'}catch(e){$('relationResult').textContent=e.message}}
async function loadAll(){try{let rows=await api('/members');$('allMembers').innerHTML=rows.map(p=>`<div class="item"><b>${esc(p.Name)}</b> — ID ${p.Person_id}<br>${esc(p.Mobile||'')} · ${esc(p.Mail_id||'')}<br><button onclick='showEdit(${JSON.stringify(p)})'>Edit</button> <button onclick='deleteMember(${p.Person_id})' class="danger">Delete</button></div>`).join('')}catch(e){alert(e.message)}}
function showAdd(){$('modalTitle').textContent='Add New Family Member';$('modalBody').innerHTML='<input id="aName" placeholder="Name"><input id="aDob" placeholder="Date of Birth"><input id="aDod" placeholder="Date of Death"><input id="aMobile" placeholder="Mobile"><input id="aMail" placeholder="Mail ID"><input id="aGender" placeholder="Gender"><button onclick="addMember()">Save Member</button>';$('modal').classList.remove('hidden')}
async function addMember(){try{await api('/members',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({Name:$('aName').value,DOB:$('aDob').value,DOD:$('aDod').value,Mobile:$('aMobile').value,Mail_id:$('aMail').value,Gender:$('aGender').value})});closeModal();loadAll()}catch(e){alert(e.message)}}
async function deleteMember(id){if(!confirm('Delete this member and their relationships?'))return;try{await api('/members/'+id,{method:'DELETE'});loadAll()}catch(e){alert(e.message)}}function closeModal(){$('modal').classList.add('hidden')};function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function attr(x){return esc(x)}
if(token){showLogged();loadMe().catch(()=>{$('logout').click()})}
